### ISSUE TITLE
Error when installing via TER

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/schemaker#46] opened 2015-11-04 06:19 UTC
When installing schemaker via extension manager from TER, I get the following exception when activating the extension:

> Could not scan for classes inside "/var/www/typo3test7/typo3conf/ext/schemaker/vendor/typo3/cms/typo3/sysext/extbase" which does not appear to be a file nor a folder

**Comment by NamelessCoder** [comment] 2015-11-04 09:55
Caused by `composer.json` handling of TYPO3 when not running in composer mode. The next TER release will fix that completely (but we still recommend you use composer to install dependencies).

Closing now since we can't auto-close issues when creating release tags ;)

**Closed by NamelessCoder** 2015-11-04 09:55 UTC

**Comment by cweiske** [comment] 2016-01-26 09:24
Works fine with version 3.2.0.
